-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.11.0
    hooks:
      -   id: gitlint
          stages: [commit-msg]
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.1
    hooks:
      -   id: seed-isort-config
          args: [--application-directories, "src:."]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
      -   id: isort
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-yaml
      -   id: debug-statements
      -   id: flake8
          additional_dependencies: ["flake8-bugbear == 19.3.0"]
          language_version: python3.6
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.0
    hooks:
      -   id: rst-backticks
