version: 2.1

executors:
  py36:
    docker:
      - image: circleci/python:3.6

commands:
  setup:
    steps:
      - checkout
      - run: sudo pip install tox
      - restore_cache:
          keys:
            - v1-tox-{{ checksum "tox.ini" }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/dev.txt" }}
      - run: tox --notest
      - save_cache:
          key: v1-tox-{{ checksum "tox.ini" }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - .tox

jobs:
  flake8:
    executor: py36
    steps:
      - setup
      - run: tox -e flake8

  mypy:
    executor: py36
    steps:
      - setup
      - run: tox -e mypy

  isort:
    executor: py36
    steps:
      - setup
      - run: tox -e isort

  tests:
    executor: py36
    steps:
      - setup
      - run: tox -e py3-tests
      - run: tox -e coverage

workflows:
  version: 2

  build:
    jobs:
      - flake8
      - mypy
      - isort
      - tests
